### ISSUE TITLE
Publish MeltanoLabs Slack App

### ISSUE THREAD

**Issue by stkbailey** [MeltanoLabs/tap-slack#4]
Currently, prospective users of the tap would need to go into Slack and create a custom app. But, it would be simple to create and list an App on the Slack App Marketplace. This would make it easy to install (and get the MeltanoLabs logo out there). It would also be able to provide some confirmation to prospective users that the app will not have permissions to read private messages, private channels, etc.

- [] Agree on App manifest and permissions
- [] Ensure that App permissions work in multiple environments
- [] Get full high quality logo and figure out ownership concerns.

![Screenshot from testing environment](https://user-images.githubusercontent.com/7850417/138863905-4d48e41e-e8a6-4514-bb30-6286d50b5404.png)

**Comment by tayloramurphy** [comment]
@aaronsteers what are your thoughts on the above?

**Comment by aaronsteers** [comment]
@tayloramurphy and @stkbailey - I really like this idea, actually. We'd want to do this in a supportable manner - and I think the list of prereqs + prep steps to "do it right" is probably pretty long.

Notably, I'd want these in place to know we have decent maintainability long-term:

- PyPi if we don't have it here already here.
- CI testing.
- Auto-push to PyPi in CI.
- A solid "how to" doc we can publish to the Slack marketplace.
- Optionally, a youtube video showing the process.

If this were not SDK based, I'd be very concerned about long-term support of the codebase itself. But because it is SDK based, and since the code is so far in very good condition, I'm really much less concerned about our support liability on the actual tap. Worst case: we'd submit to get it removed if, for instance, Slack tomorrow deprecated/replaced their entire API. I think the larger risk is stabilty of PyPi versions, ability to efficiently test and republish, and having a good documentation to keep support costs down.

Other thoughts on the pros and cons:

Pros:

- We get the Meltano/Singer names out there and provide a compelling interface for people to own their own Slack data. 
- For users who want to do this anyway, its a smoother path.
- Could be a nice trial-run and learning tool for other 3rd party marketplace integrations in the future. 

Cons:

- Time used. (Can be mitigated through community support, and/or just a longer time horizon for delivery.)
- Risk to brand. (Although I think it's likely more of a positive for the brand than negative.)

Things to confirm:

- If I understand the setup here correctly, we're not committing to any SaaS or always-on support - just a streamlined interface (which Slack will maintain) by which people can get an auth tokenset to embed in their own tap config. If that's not right, and we'd need more infra, then I'd want to better understand that before committing.
